version: "3.9" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  mongodb:
    image: mongo
    restart: always
    container_name: weather-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users
    volumes:
      - ./.docker/mongodb/data:/data/db
      - ./.docker/mongodb/logs:/data/logs
    networks:
      - server-network

  server:
    container_name: weather-server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # 宿主:镜像
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - server-network

  nginx:
    container_name: weather-web
    restart: always
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - server-network
    depends_on:
      - server
      - mongodb

networks:
  server-network: